---
- project:
    vars:
      ensure_tox_version: '<4'
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-rook-ceph-tox-py39
        - k8sapp-rook-ceph-tox-flake8
        - k8sapp-rook-ceph-tox-pylint
        - k8sapp-rook-ceph-tox-metadata
        - k8sapp-rook-ceph-tox-bandit
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-rook-ceph-tox-py39
        - k8sapp-rook-ceph-tox-flake8
        - k8sapp-rook-ceph-tox-pylint
        - k8sapp-rook-ceph-tox-metadata
        - k8sapp-rook-ceph-tox-bandit
    post:
      jobs:
        - stx-rook-ceph-apps-upload-git-mirror

- job:
    name: k8sapp-rook-ceph-tox-py39
    parent: openstack-tox-py39
    description: |
      Run py39 test for k8sapp_migration_rook_ceph
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/update
      - starlingx/utilities
      - starlingx/root
    files:
      -python3-k8sapp-migration-rook-ceph/*
    vars:
      python_version: 3.9
      tox_envlist: py39
      tox_extra_args: -c python3-k8sapp-migration-rook-ceph/k8sapp_migration_rook_ceph/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-rook-ceph-tox-flake8
    parent: tox
    description: |
      Run flake8 test for k8sapp_migration_rook_ceph
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/update
      - starlingx/utilities
      - starlingx/root
    files:
      -python3-k8sapp-migration-rook-ceph/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c python3-k8sapp-migration-rook-ceph/k8sapp_migration_rook_ceph/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-rook-ceph-tox-pylint
    parent: tox
    description: |
      Run pylint test for k8sapp_migration_rook_ceph
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/update
      - starlingx/utilities
      - starlingx/root
    files:
      -python3-k8sapp-migration-rook-ceph/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python3-k8sapp-migration-rook-ceph/k8sapp_migration_rook_ceph/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-rook-ceph-tox-metadata
    parent: tox
    description: |
      Run metadata test for k8sapp_migration_rook_ceph
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/update
      - starlingx/utilities
      - starlingx/root
    files:
      -python3-k8sapp-migration-rook-ceph/*
    vars:
      tox_envlist: metadata
      tox_extra_args: -c python3-k8sapp-migration-rook-ceph/k8sapp_migration_rook_ceph/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-rook-ceph-tox-bandit
    parent: tox
    description: |
      Run bandit test for k8sapp_migration_rook_ceph
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/update
      - starlingx/utilities
      - starlingx/root
    files:
      -python3-k8sapp-migration-rook-ceph/*
    vars:
      tox_envlist: bandit
      tox_extra_args: -c python3-k8sapp-migration-rook-ceph/k8sapp_migration_rook_ceph/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: stx-rook-ceph-apps-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/rook-ceph to
      github.com/starlingx/rook-ceph
    vars:
      git_mirror_repository: starlingx/rook-ceph
    secrets:
      - name: git_mirror_credentials
        secret: stx-rook-ceph-apps-github-secret3
        pass-to-parent: true

- secret:
    name: stx-rook-ceph-apps-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - vfP+VU314+VbvzCAfpNs3B4iMfxUft3JPoIoeuezjDf1Asuz1wvs0mfm3E1MdtsKGAVcc
          8KcIhmBHgGYExpS4bJbVWR4uPUjEDWJDDupHaS+gZ69BaXaPe9y3PtH4wLciiBMTfnGjA
          75ZrlZ+fX0koqhBee4z4RLrdQdwC9oa4NV1dG/bn3ny5yrJ87nFV9v7xIxdjTZWeEgmzk
          Z6asr1gDOZPSiduqAW+I4AehwHrbv1COlZQjSu+Ukhe+BE5l/Jq2Pf7aPEDFrxu/HPCS7
          XKUjQhG/eIMG2X53yTDTXef7Bc/IDmDsI+T3PFpetVKdjc+xlhleb8yP255yHhdf1Nr7v
          aEM5HABuXW/E4+XZLJwyUyL4DNlj3P3p7Cs3sbiJbEJO3QvNn01E44jlbOF/Ze8Mrp6Zm
          EVlgI0ZLho9KvwrO9Xjc/FNjhfUK3tI6fPuYf683TrXso2cn+KM8xlC4ARo+vJADZhqVY
          CnLrJ1wgQ4o4dSiXT0g43kfcDc1lWbdpjh7m56AJOQq/3E5jmbbiCHEJuXtd9cOpz5kN8
          kr0vcrFUMiSwiyDPO0mxn3sdgzx42Sui/I2ejmoSKU9x2GpSdEF7GDtHAdarQL2sO47eN
          NIpIWcHlwy/ApQkJtN02kCJ3p9HuU+ojA4q3mZqLZF9+abnrGGb+liHUGFmT8U=
        - hSoBvghKD/hGHABRyQjh8MdzmVgUGfREXiywjOD/Nw9fvMLV3iOCVVSX3yAR2wO/m3+Jc
          gBEE8ENvCvsIv2+jYbJOY0pW8yzpvUFr7Ob74TuQkpggazEOBVNtaKK74SdjVvVSPkRYz
          Kirso7UoIOHCg/wSkDgNYY2mKO5YiwLG5U+I4aNBp6aWBlwhkek183tuyrV4/zjB1eBEH
          n3ktUo7c3me3ZkiwMP3cZX/0aiafzyT4eq+cKHoUlQjD+ss+LiWsCBI6lXjUqlkLP6z21
          erMM4tM1ZlGVhyQ+fLdadnW0H9skWF98mgq20FSaYNIoCBhUbfZTjdtZzUWLTAXhWUoMV
          QuDPUCafINKtFIbHrifdKULns3ebm/1n6quI25MhWLFQZASpPzUDknGMB5tS/rqA0dFA0
          c2tWqoCr3ZRziK4Ew2lqxgA55jNryPocgX+2TQR4fpMQG7jpJCl2V23aipFNrvaiTPT7q
          TbFv4+W7x8TIsHW79c8q0E0YgFfcwJ00mMnVGHGZUjiqRn0z+MkxrfQQQ9N0eOAcocrba
          a/IRr2JXxjsXhaOBcTtVRd9Piu4W+BPj1Zw1Hs22zmMBpo5NCC4ht2QDjU4koM56346mo
          08Chxay47wkGkUMOw7v9t3FAbOASU2Jo2yjX/rG3WNhXnrOyrthpSXf48A2Yw8=
        - RoApiaoRC0c8NLzcM7013MbtDsikjLhADJSYrobtxAq3xW64yLJch1LGmQOSS21Zq/vgI
          yAz/B1J6VNvQBCmJFBbWNC4uKbeCp7dAbGKSYFA9XpaMRtYCztS3d6BjPFnB5MKCtHp1S
          CzhuP+YmkQwjM8HuQ4BZfIcz6jT5UOnpBKnCM53Dz1gRQWIYYOrha28jipvSL8UnQlRer
          P5QUgSMh00ix2QB7ltDQjy5GUBCJ1206u0pFlNz66nhbegPabNwvrD8VRhIRKA7tcZ8xA
          rFneE+QJTWNz36155SCDTHvIR5Tv1K9frAsO90lmLDN2/jXXJLYbXEuIkfxisULWyngs1
          sEv3UW/zSd6TMWVzI1QpW1oGL9A3adpMPLpTdXqspSqiFryMQAvYhEWAGxb/0IXA1MkIV
          r6hmvOe1wAYy2CMG2FfosU8uJu7ot0XZ7WAuseHnAKXwFdS9ptpaZ5qxrJHx8COO3Hi6d
          JROhyUPqVnieyLgJlg8bF9/AiBy9N1Is2tAlLnYAlADzYiMvd25vOSW2PDVKKPBN5cs3Y
          67inkjdN7+r4S4WyyapKVw7HlHABTGwbl/epWhKMuN3qv7bOTEbvqXQJ8Ns79vrJnnIBd
          jd94ncgbkg+BYl2PIwWzu+SONNYTJl3+9AQWTR7Bg4yqPZLqeztGOBGpvYQDhQ=
        - SMTcpJ1qOUy9vYAJJRtUWItXZkMG0AaaMI/8AYHEwIwrFYBM6EXKZlx1ynrbvpCYdp2TR
          5DD3eCVnV8qB+DQ1ze4zVJYXSR8TKx5JAKrZYFgpRuSohX+mc4SW6YSFOjfY9Sjul+JcA
          2ip57QWHsuM0VHCorrTZIZJlZ78ZkN6wReNtuhyqG6yQ+59Fj0S59y3wrqPnFAa4hGzYA
          ue+5W1JtIaBFHQdKJOuHMrri7VeB/DIDluf3LFm+sZSR8Eb059As1dtFVcu7xi7s0ONkg
          bn/OZCkxL0krBi/TbpaoR8G7Y/r+byPdXOZEWe0B5snn4lAEjivgjBylhrvLA/9By5N34
          n725NiuOZwynUvg912v+IxqHjrW+j6f8mWQI2md2T7/xSkmTXUm4jSFihmejP8U1wASNV
          not1VYVuHP3eQYe0LUgsPP+SMs/UfRwI4FwkoSIlLN4oJgRmnlusCWvI/EDCODVgC+59z
          p1uZJjlUGy5GVzazyXXzpmKsmf087lNMLweXx/ZWXC4qXRT6urh7BWPdgpNg5UP/EfB0z
          EaqrzIvQDr5BaPGnPFLoRVSiAXgxwYtt9m8e0ek0BEdjCj5jd93itveK0Vn3k+zDsqne+
          CtL7j34uKSTieu+hJm+2aCoC7D99F6GtE4CkJA3Y51slW6dFwOhW68yUpHaGqA=
        - UGMMz6TYNkwuUnrBpDy+iErFcj+vnrkHuoYTScWA8rf+DpyUsdkOXSAw9cuKQOXYAJOxj
          Z4JJv2Bi0xMn+H26txOG9Slyxhc0A6VBZzXbVCWeynNzDTkK8j61bOZLC2HeUWBL9KV53
          zXfSY4D8bKtV5acG2X/+w53YyWyd7GHTzotvKAgNq9kOy36ll9/WIllzYxOWsDQyHcOqt
          TYFgsQT5ylCLtCQ91gvc43U5gYHl0QTXTuyzEBas1QVblbDsX6HIJOa309lkoY6yVA+x8
          u0KG/4eQdWw50B15Rsae1js5ERlBnEff/wAKwp13mHFMoY9AA+x5f3jXTgvqfEeMrsWhg
          WepcWrcvb4LSG2z9Dyt1vM9FO/vVemdoejNJ8SOnxtBQuYZP45Mgv2CINHxEYCjwgXVkV
          CAUmQnEtLFGb+BFe+S1Y4XCA+EqRxNgvu2G4iI0o2OMK6/nlvCj8P2WtFI9w74D5h1z5p
          N4AvIqVGjY+fMoxaAjbhzER1NR71DGP5BAL34eOWnMmfWkD3cGwg2BgsdnAyURfXi+Mrw
          KAI7sci4Ffr1t9LROXchFyTm6CpHjp2hTDbRj3+0x6RpLPVjUvoqosFOlb9bj5oQCm5Xy
          kDzR+mX+qQPNbe9YASqeZEwO9nZz2/BlTp7iZCStt6fDvZZzHhx5cHX9tJ7Bco=
        - JnKqTYY3Huzse0w22KljxgieQ5n/aLYoCq67a3Dw+S/G0u6VCoVxgEVfUqYjogVbPGhpB
          Y+LvIXcz7wGDrcJG7hL2mTDF7sXk4PVLQI8axZz6uxDHAE9XEzz5L1UOSWZFO1KVtUgkz
          aMvPvHDO34Kau5TBy5X12oRH4JeojK9E4GlG1cyIUrD75bQ6R8s7inIbs6MXbM2qCMeB7
          XUp8snVuQ75fiHIFGa5ggQIHmct6vvU9VIDNwpOQm2q6iUwt/DbYbua6OgZVzCOJRYYcm
          rWjKaG3Md6NKI55Anro3tw1TheLIwoSl4k+HMtPKm6ZfJl4w/Kydw8+7OTqF34//9bNV+
          7u56gkq08rM47sBFcFmSwEsN7kCQ8gLbM84brN/gjzgC1yEPYlNEuQyMKr29dR0D6Duvz
          bbHv/pKN3Venzw2JHJDwlRbF2BLulEq+ycISXfeKv+l6AwKx4oS1jfms2JiDzmPYBoYoT
          IAERwWAqFTWxAHlP4XURkFs+um3ftJlMm920ushbT9C+RDoKXftr9PiQQq+FET6cuO8i1
          cF/y/I7Y0ajqgLX2lIiKW0/OEHQfSuFC6OcC9rdJRThrXmLiDF6UJnUCsL96H7k0CA92Q
          QpnhwWox7/jp8r7yKP+KI7uNK+jaR0bojSJVrL6jDbvv1d5xlpKBqAm1H5wiro=
        - mRx0Ch60m1M+iJzXm9pWe2tLMvThzsU2S7AIMKoofub4mHORRHu8OitJiPH5PE21TMDvW
          4WCCdE09oJGJinLybs4IAcKfiYXCnJrNZfqeTa2qM1YnqDbBgRmH7DPCAUwJ3tX1YFo9f
          3kTKV2tf4MOBfFP6dNqKJCIp+fO9RIReIVwPmUjZAe5ivVxkPe6p/jmRGo3z77Sn8Hch4
          vnsfca3DeD5ZpwnMaqrSHAMzFoyxSmCLzl/6nrDOTq1nUxOIOzC22qFCSioAbMIqVqJO0
          fLYlDpvv0TnpL4Xb3bmeC7Z6BcMBCHwcmH2Qrywhzmy2zeWUZ2Mhu+BN8qyVS064oulQv
          usJiQLHSv9SHuyrg+REGUA0xlyRG86f+dloyWSX3t/GfKeSZBvsXY9bzEkTdvSt02fUes
          hYvBFpeSEz66Rtn65L6pKpUW/XNeu+5nA9lTC9n/TWqRAEzTSw7GHoDAwfbsZ1H08uKtW
          k+a0iAPxY+fJWLakpE7FmU7ioshylxHFKsSLTDdJKm+Tkp4/foiW7/nx4TGdemI9MU4yH
          0ejrgyYztkxcsxz0UZw3RPo133aYWWAFHo6PA/Uq06BiHruNr5WbMRAdVDM/DEHbwKxM7
          wysIpvy9K37BXsiEOc9LvJSinPmE1JivcYqcsyAbY6/c47doparbiSENu8It74=
