{{/*
#
# Copyright (c) 2018 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{ if .Values.hook.cleanup.enable }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.hook.cleanup.rbac.clusterRole }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "list", "update", "delete"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "create", "list", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get", "create", "list", "update", "delete"]
{{- end}}
