{{/*
#
# Copyright (c) 2020 Intel Corporation, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- if .Values.hook.duplexPreparation.enable }}
{{ $root := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-rook-ceph-duplex-preparation
  namespace: {{ $root.Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
data:
  rook_duplex_preparation.sh: |-
    #!/bin/bash

    cat >  endpoint.yaml << EOF
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: rook-ceph-mon-endpoints
      namespace: $NAMESPACE
    data:
      data: a=$FLOAT_IP:6789
      mapping: '{"node":{"a":{"Name":"$ACTIVE_CONTROLLER","Hostname":"$ACTIVE_CONTROLLER","Address":"$FLOAT_IP"}}}'
      maxMonId: "0"
    EOF

    kubectl apply -f endpoint.yaml

    rm -f endpoint.yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: rook-ceph-duplex-preparation
  namespace: {{ $root.Release.Namespace }}
  labels:
    heritage: {{$root.Release.Service | quote }}
    release: {{$root.Release.Name | quote }}
    chart: "{{$root.Chart.Name}}-{{$root.Chart.Version}}"
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  template:
    metadata:
      name: rook-ceph-duplex-preparation
      namespace: {{ $root.Release.Namespace }}
      labels:
        heritage: {{$root.Release.Service | quote }}
        release: {{$root.Release.Name | quote }}
        chart: "{{$root.Chart.Name}}-{{$root.Chart.Version}}"
    spec:
      serviceAccountName: rook-ceph-system
      restartPolicy: OnFailure
      volumes:
        - name: config-rook-ceph-duplex-preparation
          configMap:
            name: config-rook-ceph-duplex-preparation
      containers:
        - name: duplex-preparation
          image: {{ .Values.hook.image }}
          command: [ "/bin/bash", "/tmp/mount/rook_duplex_preparation.sh" ]
          env:
            - name: NAMESPACE
              value: {{ $root.Release.Namespace }}
            - name: ACTIVE_CONTROLLER
              value: {{ $root.Values.hook.duplexPreparation.activeController }}
            - name: FLOAT_IP
              value: {{ $root.Values.hook.duplexPreparation.floatIP }}
          volumeMounts:
            - name: config-rook-ceph-duplex-preparation
              mountPath: /tmp/mount
{{- end }}
