{{/*
#
# Copyright (c) 2018 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{ if .Values.hook.cleanup.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.hook.cleanup.rbac.serviceAccount }}
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
  - name: default-registry-key
{{- end }}
