{{/*
#
# Copyright (c) 2019 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- if .Values.global.job_ceph_osd_audit }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-osd-audit-bin
  namespace: {{ .Release.Namespace }}
data:
  osd_audit.py: |-
{{- include "script.osd_audit" . | indent 4 }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: stx-ceph-osd-audit
spec:
  schedule: {{ .Values.ceph_audit_jobs.audit.cron | quote }}
  startingDeadlineSeconds: {{ .Values.ceph_audit_jobs.audit.deadline }}
  successfulJobsHistoryLimit: {{ .Values.ceph_audit_jobs.audit.history.success }}
  failedJobsHistoryLimit: {{ .Values.ceph_audit_jobs.audit.history.failed }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      name: stx-ceph-osd-audit
      namespace: {{ .Release.Namespace }}
      labels:
        app: ceph-osd-audit
    spec:
      template:
        metadata:
          labels:
            app: ceph-osd-audit
        spec:
          serviceAccountName: {{ .Values.rbac.serviceAccount }}
          restartPolicy: OnFailure
          hostNetwork: true
          {{- if .Values.global.nodeSelector }}
          nodeSelector:
          {{ .Values.global.nodeSelector | toYaml | trim | indent 10 }}
          {{- end }}
          volumes:
          - name: ceph-osd-audit-bin
            configMap:
              name: ceph-osd-audit-bin
              defaultMode: 0555
          - name: kube-config
            hostPath:
              path: /etc/kubernetes/admin.conf
          - name: config-key-provision
            configMap:
              name: {{ .Values.global.configmap_key_init }}
          - name: ceph-config
            emptyDir: {}
          initContainers:
          - name: init
            image: {{ .Values.images.tags.ceph_config_helper | quote }}
            command: [ "/bin/bash", "/tmp/mount/provision.sh" ]
            env:
            - name: ADMIN_KEYRING
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-admin-keyring
                  key: keyring
            - name: ROOK_MONS
              valueFrom:
                configMapKeyRef:
                  name: rook-ceph-mon-endpoints
                  key: data
            volumeMounts:
            - name: ceph-config
              mountPath: /etc/ceph
            - name: config-key-provision
              mountPath: /tmp/mount
          containers:
          - name: ceph-osd-audit
            image: {{ .Values.images.tags.stx_ceph_manager | quote }}
            command: [ "python", "/tmp/mount/osd_audit.py" ]
            env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            volumeMounts:
            - name: ceph-osd-audit-bin
              mountPath: /tmp/mount
            - name: ceph-config
              mountPath: /etc/ceph
              readOnly: true
            - name: kube-config
              mountPath: /etc/kubernetes/admin.conf
              readOnly: true
{{- end }}
