{{/*
#
# Copyright (c) 2020 Intel Corporation, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- if .Values.global.job_host_provision }}
{{ $root := . }}
{{- range $controller_host := $root.Values.host_provision.controller_hosts }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "rook-ceph-host-provision-{{ $controller_host }}"
  namespace: {{ $root.Release.Namespace }}
  labels:
    heritage: {{ $root.Release.Service | quote }}
    release: {{ $root.Release.Name | quote }}
    chart: "{{$root.Chart.Name}}-{{$root.Chart.Version}}"
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  template:
    metadata:
      name: "rook-ceph-host-provision-{{ $controller_host }}"
      namespace: {{ $root.Release.Namespace }}
      labels:
        heritage: {{ $root.Release.Service | quote }}
        release: {{ $root.Release.Name | quote }}
        chart: "{{$root.Chart.Name}}-{{$root.Chart.Version}}"
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: rook-conf
          hostPath:
            path: /etc/ceph/
        - name: config-key-provision
          configMap:
            name: {{ $root.Values.global.configmap_key_init }}
      containers:
        - name: host-provision
          image: {{ $root.Values.images.tags.ceph_config_helper | quote }}
          command: [ "/bin/bash", "/tmp/mount/provision.sh" ]
          env:
            - name: ADMIN_KEYRING
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-admin-keyring
                  key: keyring
            - name: ROOK_MONS
              valueFrom:
                configMapKeyRef:
                  name: rook-ceph-mon-endpoints
                  key: data
          volumeMounts:
            - name: rook-conf
              mountPath: /etc/ceph/
            - name: config-key-provision
              mountPath: /tmp/mount
      nodeName: {{ $controller_host }}
{{- end }}
{{- end }}

