[metadata]
name = k8sapp_migration_rook_ceph
summary = StarlingX sysinv extensions for rook-ceph-migration app
long_description = file: README.rst
long_description_content_type = text/x-rst
license = Apache 2.0
author = StarlingX
author-email = starlingx-discuss@lists.starlingx.io
home-page = https://www.starlingx.io/
classifier =
    Environment :: OpenStack
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9

[files]
packages =
    k8sapp_migration_rook_ceph

[global]
setup-hooks =
    pbr.hooks.setup_hook

[entry_points]
systemconfig.helm_applications =
    rook-ceph-migration = systemconfig.helm_plugins.rook_ceph_apps

systemconfig.helm_plugins.rook_ceph_apps =
    001_rook-ceph = k8sapp_migration_rook_ceph.helm.rook_ceph:RookCephHelm
    002_rook-ceph-cluster = k8sapp_migration_rook_ceph.helm.rook_ceph_cluster:RookCephClusterHelm
    003_rook-ceph-provisioner = k8sapp_migration_rook_ceph.helm.rook_ceph_provisioner:RookCephClusterProvisionerHelm

systemconfig.fluxcd.kustomize_ops =
    rook-ceph-migration = k8sapp_migration_rook_ceph.kustomize.kustomize_rook_ceph:RookCephFluxCDKustomizeOperator

systemconfig.app_lifecycle =
    rook-ceph-migration = k8sapp_migration_rook_ceph.lifecycle.lifecycle_rook_ceph:RookCephAppLifecycleOperator

[wheel]
universal = 1
