{{/*
#
# Copyright (c) 2020 Intel Corporation, Inc.
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- if .Values.global.job_cleanup }}
{{ $root := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-rook-provisioner-cleanup
  namespace: {{ .Release.Namespace }}
data:
  rook_clean_up.sh: |-
    #!/bin/bash

    kubectl delete configmap -n ${NAMESPACE} ceph-etc
    kubectl delete secret -n rook-ceph ${CEPH_ADMIN_SECRET}
    kubectl delete secret -n rook-ceph ${CEPH_USER_SECRET}

    echo "rook ceph provisioner cleanup"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: rook-provisioner-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{$root.Chart.Name}}-{{$root.Chart.Version}}"
  annotations:
    "helm.sh/hook": "pre-delete"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  template:
    metadata:
      name: rook-provisioner-cleanup
      namespace: {{ .Release.Namespace }}
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{$root.Chart.Name}}-{{$root.Chart.Version}}"
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Values.rbac.serviceAccount }}
      volumes:
        - name: config-rook-provisioner-cleanup
          configMap:
            name: config-rook-provisioner-cleanup
      containers:
        - name: rook-provisioner-cleanup
          image: {{ .Values.images.tags.ceph_config_helper | quote }}
          command: [ "/bin/bash", "/tmp/mount/rook_clean_up.sh" ]
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: CEPH_ADMIN_SECRET
              value: {{ .Values.provisionStorage.classdefaults.adminSecretName }}
            - name: CEPH_USER_SECRET
              value: {{ .Values.provisionStorage.classes.secret.userSecretName }}
          volumeMounts:
            - name: config-rook-provisioner-cleanup
              mountPath: /tmp/mount
{{- end }}
